### ISSUE TITLE
Add activation code to registration

### ISSUE THREAD

**Issue by ezraholm50** [ezraholm50/server-client#1]
Het zou mooi zijn als men de activatie code van een device kan mee geven tijdens de registratie en deze meteen in de interface komt te staan.

**Comment by timmeh1955** [comment]
Welke interface bedoel je?
De activatiecode staat in de UI op de server. Alleen inzichtelijk voor de admin.
Zodra de rpi geactiveerd is, is de activatiecode niet meer beschikbaar.
