### ISSUE TITLE
webclient registration screen refresh interval

### ISSUE THREAD

**Issue by ezraholm50** [ezraholm50/server-client#5]
Web page showing the device ID and activation code refreshes every 5 seconds or so, can we have this set to every minute?

**Comment by timmeh1955** [comment]
Hi Ezra,

Dat zijn veel vragen. Ik verzamel ze even. Zijn we al toe aan iets als Trello?

1. Dankje ik kan er in! kun je mij admin maken?
Done.
pw: Test1234

2. De client werkt bij mij niet met de huidige files in server-client/client/python, werkt het bij jou wel? (ik krijg geen activatie code op de client PI)
Ja. werkt. Ik denk dat deze opmerking inmiddels achterhaald is.

3. Troubleshooten
Zodra ik het autoinstall heb gedaan, kan ik je beter helpen.

4. Demo
Wat vind je hier van <https://jfhyhm5jizaaoziq.anvil.app/5DHS6Y3OUEPYFB2DWNIS3RJV>
Ziet er leuk uit.

5. Proberen autoinstall script:
ga ik doen. Ik denk donderdag.
v0.1-alpha

6. /home/remote/.ssh/authorized_keys
Ik zie dat er al een dergelijk bestand is. Kan ik dat overschrijven?
Overigens, de id_rsa.pub waarden, bewaar ik in de database. Als een key wordt toegevoegd of een rpi is niet meer actief, overschrijf ik het hele bestand. Toevoegingen die handmatig of op een andere manier zijn gedaan, gaan dus geregeld verloren.

7. "klaarzetten van een commando om het password op de rpi aan te passen."
Daar bedoel ik mee: De admin kan standaard commando's opgeven. In enkele gevallen moet daar een password worden ingevuld. Dus als in jouw commando staat $PASSWORD, dan zet de server het password er in en geeft het aan de rpi. Die stap heb ik nog niet.

8. "vermeldingen van /home/pi naar /home/dietpi gezet, welke moeten er nog meer wijzigen?"
Ik weet natuurlijk niet wat er anders is met dietpy. Zodra ik dat werkend heb, kan ik dit beantwoorden.

9. "Web page refreshes every 5 seconds"
Die 5 seconden is alleen als de rpi nog niet geactiveerd is.
Zodra het geactiveerd is, gaat het naar iedere minuut.
Het criterium is: activation_code == gevuld of leeg.

Groeten
